{% set name = "seeq" %}
{% set version = "61.2.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/seeq-{{ version }}.tar.gz
  sha256: 5f0362b641a0e5022dff7b55d2002ab8e9fd2c15ec7dc9dfe31d589eb6079e3f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - pip
    - wheel
  run:
    - python
    - certifi >=14.05.14
    - six >=1.10
    - urllib3 >=1.15.1,<2.0.0
    - requests >=2.21.0
    - cryptography >=3.2

test:
  imports:
    - seeq.sdk
    - seeq.sdk.api
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://www.seeq.com
  summary: The Seeq SDK for Python
  license: AGPL-3.0
  license_file: LICENSE
  dev_url: https://www.seeq.com
  doc_url: https://www.seeq.com

extra:
  anaconda-services:
    ref: https://anaconda.zendesk.com/agent/tickets/49247
    reason: Client request
  recipe-maintainers:
    - ianaobi
